name: check-package-version
on: [push]
jobs:
  check-package-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check local version is newer
        id: check
        uses: EndBug/version-check@v1.6.0
        with:
          diff-search: true
          file-name: ./package.json
          file-url: https://unpkg.com/@data-provider/react@latest/package.json
          static-checking: localIsNew
      - name: Fail when version not upgraded
        if: steps.check.outputs.changed != 'true'
        run: |
          echo "Version not upgraded"
          exit 1
